-- StreamDeck Keybind Installer
-- Class: Warrior Protection
-- Generated by streamdeck-generator
--
-- INSTRUCTIONS:
-- 1. Copy this ENTIRE script
-- 2. Paste into WoW chat (/paste if you have paste addon)
--    OR create a macro and paste it there, then run the macro
-- 3. Type /reload to apply changes
--
-- WARNING: This will CLEAR ALL existing keybinds!
-- Make a backup first if you want to preserve current settings.

function Install()
  print("StreamDeck: Clearing existing keybinds...")
  
  -- Clear ALL existing bindings
  LoadBindings(1) -- Load current bindings
  for i = 1, GetNumBindings() do
    local command = select(1, GetBinding(i))
    if command then
      for j = 1, 2 do -- Clear both primary and secondary
        local key = select(j + 1, GetBinding(i))
        if key and key ~= "" then
          SetBinding(key, nil)
        end
      end
    end
  end
  
  print("StreamDeck: Installing new keybinds...")
  
  -- Arrow Key Movement
  SetBinding("UP", "MOVEFORWARD")
  SetBinding("DOWN", "MOVEBACKWARD")
  SetBinding("LEFT", "TURNLEFT")
  SetBinding("RIGHT", "TURNRIGHT")
  
  SetBinding("Y", "TOGGLEACHIEVEMENT")
  SetBinding("1", "ACTIONBUTTON1")
  SetBinding("0", "ACTIONBUTTON2")
  SetBinding("-", "ACTIONBUTTON3")
  SetBinding("=", "ACTIONBUTTON4")
  SetBinding("2", "ACTIONBUTTON5")
  SetBinding("3", "ACTIONBUTTON6")
  SetBinding("4", "ACTIONBUTTON7")
  SetBinding("5", "ACTIONBUTTON8")
  SetBinding("6", "ACTIONBUTTON9")
  SetBinding("7", "ACTIONBUTTON10")
  SetBinding("8", "ACTIONBUTTON11")
  SetBinding("9", "ACTIONBUTTON12")
  SetBinding("SHIFT-J", "ACTIONBUTTON13")
  SetBinding("ALT-F8", "ACTIONBUTTON14")
  SetBinding("CTRL-F12", "ACTIONBUTTON15")
  SetBinding("NUMPADDECIMAL", "ASSISTTARGET")
  SetBinding("NUM LOCK", "TOGGLEAUTORUN")
  SetBinding("NUMLOCK", "TOGGLEAUTORUN")
  SetBinding("F9", "ACTIONBUTTON16")
  SetBinding("CTRL-F7", "ACTIONBUTTON17")
  SetBinding("SHIFT-F7", "ACTIONBUTTON18")
  SetBinding("ALT-F1", "ACTIONBUTTON19")
  SetBinding("C", "ACTIONBUTTON20")
  SetBinding("SHIFT-CTRL-F6", "TOGGLECHARACTER0")
  SetBinding("NUMPAD8", "ACTIONBUTTON21")
  SetBinding("NUMPADADD", "CLEARFOCUS")
  SetBinding("SHIFT-CTRL-F7", "TOGGLECOLLECTIONS")
  SetBinding("NUMPAD0", "ACTIONBUTTON22")
  SetBinding("CTRL-F10", "ACTIONBUTTON23")
  SetBinding("NUMPAD3", "ACTIONBUTTON24")
  SetBinding("F10", "ACTIONBUTTON25")
  SetBinding("NUMPAD7", "ACTIONBUTTON26")
  SetBinding("ALT-F3", "ACTIONBUTTON27")
  SetBinding("ALT-F10", "ACTIONBUTTON28")
  SetBinding("SHIFT-F10", "ACTIONBUTTON29")
  SetBinding("CTRL-F6", "ACTIONBUTTON30")
  SetBinding("I", "ACTIONBUTTON31")
  SetBinding("SHIFT-CTRL-F11", "TOGGLEENCOUNTERJOURNAL")
  SetBinding("(UNBOUND BY DEFAULT", "ACTIONBUTTON32")
  SetBinding("CTRL-F11", "ACTIONBUTTON33")
  SetBinding("SHIFT-F11", "ACTIONBUTTON34")
  SetBinding("ALT-F12", "ACTIONBUTTON35")
  SetBinding("SHIFT-F4", "ACTIONBUTTON36")
  SetBinding("SHIFT-F5", "ACTIONBUTTON37")
  SetBinding("SHIFT-F6", "ACTIONBUTTON38")
  SetBinding("NUMPADSUBTRACT", "FOCUSTARGET")
  SetBinding("SHIFT-F9", "ACTIONBUTTON39")
  SetBinding("CTRL-ALT-1", "TOGGLESOCIAL")
  SetBinding("SHIFT-V", "ACTIONBUTTON40")
  SetBinding("ESCAPE", "TOGGLEGAMEMENU")
  SetBinding("CTRL-F5", "ACTIONBUTTON41")
  local mId = GetMacroIndexByName("Great Vault")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Great Vault", "inv_misc_questionmark", "/run LoadAddOn(\"Blizzard_WeeklyRewards\"); WeeklyRewardsFrame:Show()", 1)
  SetBindingMacro("SHIFT-CTRL-F3", "Great Vault")
  SetBinding("ALT-F11", "ACTIONBUTTON42")
  SetBinding("J", "ACTIONBUTTON43")
  SetBinding("NUMPAD1", "ACTIONBUTTON44")
  SetBinding("CTRL-F2", "ACTIONBUTTON45")
  SetBinding("F12", "ACTIONBUTTON46")
  SetBinding("F8", "ACTIONBUTTON47")
  SetBinding("F", "INTERACTTARGET")
  SetBinding("F", "ACTIONBUTTON48")
  SetBinding("B", "ACTIONBUTTON49")
  SetBinding("CTRL-F3", "ACTIONBUTTON50")
  SetBinding("CTRL-ALT-4", "ACTIONBUTTON51")
  SetBinding("SPACE", "ACTIONBUTTON52")
  SetBinding("F7", "ACTIONBUTTON53")
  SetBinding("CTRL-ALT-5", "ACTIONBUTTON54")
  SetBinding("SHIFT-CTRL-F12", "TOGGLEGROUPFINDER")
  SetBinding("ALT-F4", "ACTIONBUTTON55")
  SetBinding("NUMPAD5", "ACTIONBUTTON56")
  SetBinding("M", "CLICK CompanionsMicroButton:LeftButton")
  SetBinding("S", "MOVEBACKWARD")
  SetBinding("W", "MOVEFORWARD")
  SetBinding("V", "ACTIONBUTTON57")
  SetBinding("B", "OPENALLBAGS")
  SetBinding("ESCAPE", "ACTIONBUTTON58")
  SetBinding("G", "ACTIONBUTTON59")
  SetBinding("SHIFT-T", "ACTIONBUTTON60")
  SetBinding("CTRL-F8", "ACTIONBUTTON61")
  SetBinding("CTRL-F9", "ACTIONBUTTON62")
  SetBinding("K", "ACTIONBUTTON63")
  SetBinding("ALT-F5", "ACTIONBUTTON64")
  SetBinding("NUMPADMULTIPLY", "ACTIONBUTTON65")
  SetBinding("F11", "ACTIONBUTTON66")
  SetBinding("H", "ACTIONBUTTON67")
  SetBinding("L", "ACTIONBUTTON68")
  SetBinding("SHIFT-CTRL-F1", "ACTIONBUTTON69")
  SetBinding("NUMPADDIVIDE", "ACTIONBUTTON70")
  local mId = GetMacroIndexByName("Reload UI")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Reload UI", "inv_misc_questionmark", "/reload", 1)
  SetBindingMacro("SHIFT-CTRL-F2", "Reload UI")
  SetBinding("ALT-F7", "ACTIONBUTTON71")
  SetBinding("R", "ACTIONBUTTON72")
  SetBinding("SHIFT-F8", "ACTIONBUTTON73")
  SetBinding("U", "ACTIONBUTTON74")
  SetBinding("SHIFT-F12", "ACTIONBUTTON75")
  SetBinding("PRINT SCREEN", "SCREENSHOT")
  SetBinding("F6", "ACTIONBUTTON76")
  SetBinding("X", "ACTIONBUTTON77")
  SetBinding("NUMPAD2", "ACTIONBUTTON78")
  SetBinding("ALT-F6", "ACTIONBUTTON79")
  SetBinding("GUILD", "ACTIONBUTTON80")
  SetBinding("CTRL-F4", "ACTIONBUTTON81")
  SetBinding("SHIFT-CTRL-F10", "TOGGLESPELLBOOK")
  SetBinding("P", "ACTIONBUTTON82")
  SetBinding("NUMPAD4", "ACTIONBUTTON83")
  SetBinding("NUMPAD9", "ACTIONBUTTON84")
  SetBinding("Q", "STRAFELEFT")
  SetBinding("E", "STRAFERIGHT")
  local mId = GetMacroIndexByName("Stuck")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Stuck", "spell_shadow_teleport", "/run Stuck()", 1)
  SetBindingMacro("SHIFT-CTRL-F9", "Stuck")
  SetBinding("ALT-F2", "ACTIONBUTTON85")
  SetBinding("SHIFT-F1", "ACTIONBUTTON86")
  SetBinding("SHIFT-F2", "ACTIONBUTTON87")
  SetBinding("SHIFT-F3", "ACTIONBUTTON88")
  SetBinding("SHIFT-F (DEFAULT SETTING FOR INTERACT KEY AS F", "ACTIONBUTTON89")
  SetBinding("F2", "ACTIONBUTTON90")
  SetBinding("F3", "ACTIONBUTTON91")
  SetBinding("F4", "ACTIONBUTTON92")
  SetBinding("F5", "ACTIONBUTTON93")
  SetBinding("SHIFT-CTRL-F8", "TARGETNEARESTENEMY")
  SetBinding("TAB", "ACTIONBUTTON94")
  SetBinding("F1", "ACTIONBUTTON95")
  SetBinding("SHIFT-TAB", "TARGETPREVIOUSENEMY")
  SetBinding("F1 (OR SOMETIMES JUST THE ASSIGNED KEY IF SET IN OPTIONS)", "TARGETSELF")
  SetBinding("ALT-Z", "ACTIONBUTTON96")
  SetBinding("SHIFT-MOUSE WHEEL DOWN (SCROLL DOWN)", "ACTIONBUTTON97")
  SetBinding("SHIFT-MOUSE WHEEL UP (SCROLL UP)", "ACTIONBUTTON98")
  SetBinding("ENTER", "ACTIONBUTTON99")
  local mId = GetMacroIndexByName("Toggle Details")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Toggle Details", "inv_misc_questionmark", "/details toggle", 1)
  SetBindingMacro("SHIFT-CTRL-F4", "Toggle Details")
  local mId = GetMacroIndexByName("Toggle Music")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Toggle Music", "inv_misc_drum_01", "/run SetCVar(\"Sound_EnableMusic\", 1 - GetCVar(\"Sound_EnableMusic\"))", 1)
  SetBindingMacro("SHIFT-CTRL-F5", "Toggle Music")
  SetBinding("L", "TOGGLEQUESTLOG")
  SetBinding("NUMPAD6", "ACTIONBUTTON100")
  SetBinding("A", "TURNLEFT")
  SetBinding("D", "TURNRIGHT")
  SetBinding("ALT-F9", "ACTIONBUTTON101")
  SetBinding("CTRL-F1", "ACTIONBUTTON102")
  SetBinding("F12", "ACTIONBUTTON103")
  SetBinding("M", "TOGGLEWORLDMAP")
  SetBinding("CTRL-ALT-2", "CAMERAZOOMIN")
  SetBinding("CTRL-ALT-3", "CAMERAZOOMOUT")
  
  -- Automated Action Bar Placement
  -- This will try to place spells automatically
  print("StreamDeck: Placing abilities on action bars...")
  local placed = 0
  local failed = 0
  
  -- AH Mount → Slot 14 (needs manual placement - item/macro)
 failed = failed + 1
  -- Flying Mount → Slot 35 (needs manual placement - item/macro)
 failed = failed + 1
  -- Ground Mount → Slot 42 (needs manual placement - item/macro)
 failed = failed + 1
  -- Health Potion → Slot 44 (needs manual placement - item/macro)
 failed = failed + 1
  -- Invis Potion → Slot 50 (needs manual placement - item/macro)
 failed = failed + 1
  -- Repair Mount → Slot 71 (needs manual placement - item/macro)
 failed = failed + 1
  -- Smart Mount → Slot 79 (needs manual placement - item/macro)
 failed = failed + 1
  -- Speed Potion → Slot 81 (needs manual placement - item/macro)
 failed = failed + 1
  
  print(string.format("StreamDeck: Placed %d abilities, %d need manual setup", placed, failed))
  
  print("StreamDeck: Keybinds installed successfully!")
  SaveBindings(2)
end

Install()