-- StreamDeck Keybind Installer
-- Class: Paladin Protection
-- Generated by streamdeck-generator
--
-- INSTRUCTIONS:
-- 1. Copy this ENTIRE script
-- 2. Paste into WoW chat (/paste if you have paste addon)
--    OR create a macro and paste it there, then run the macro
-- 3. Type /reload to apply changes
--
-- WARNING: This will CLEAR ALL existing keybinds!
-- Make a backup first if you want to preserve current settings.

function Install()
  print("StreamDeck: Clearing existing keybinds...")
  
  -- Clear ALL existing bindings
  LoadBindings(1) -- Load current bindings
  for i = 1, GetNumBindings() do
    local command = select(1, GetBinding(i))
    if command then
      for j = 1, 2 do -- Clear both primary and secondary
        local key = select(j + 1, GetBinding(i))
        if key and key ~= "" then
          SetBinding(key, nil)
        end
      end
    end
  end
  
  print("StreamDeck: Installing new keybinds...")
  
  -- Arrow Key Movement
  SetBinding("UP", "MOVEFORWARD")
  SetBinding("DOWN", "MOVEBACKWARD")
  SetBinding("LEFT", "TURNLEFT")
  SetBinding("RIGHT", "TURNRIGHT")
  
  SetBinding("Y", "TOGGLEACHIEVEMENT")
  SetBinding("1", "ACTIONBUTTON1")
  SetBinding("0", "ACTIONBUTTON2")
  SetBinding("-", "ACTIONBUTTON3")
  SetBinding("=", "ACTIONBUTTON4")
  SetBinding("2", "ACTIONBUTTON5")
  SetBinding("3", "ACTIONBUTTON6")
  SetBinding("4", "ACTIONBUTTON7")
  SetBinding("5", "ACTIONBUTTON8")
  SetBinding("6", "ACTIONBUTTON9")
  SetBinding("7", "ACTIONBUTTON10")
  SetBinding("8", "ACTIONBUTTON11")
  SetBinding("9", "ACTIONBUTTON12")
  SetBinding("SHIFT-J", "ACTIONBUTTON13")
  SetBinding("ALT-F8", "ACTIONBUTTON14")
  SetBinding("CTRL-F12", "ACTIONBUTTON15")
  SetBinding("F8", "ACTIONBUTTON16")
  SetBinding("NUMPADDECIMAL", "ASSISTTARGET")
  SetBinding("NUM LOCK", "TOGGLEAUTORUN")
  SetBinding("NUMLOCK", "TOGGLEAUTORUN")
  SetBinding("SHIFT-CTRL-F5", "ACTIONBUTTON17")
  SetBinding("CTRL-F7", "ACTIONBUTTON18")
  SetBinding("SHIFT-F7", "ACTIONBUTTON19")
  SetBinding("SHIFT-CTRL-F12", "ACTIONBUTTON20")
  SetBinding("CTRL-ALT-1", "ACTIONBUTTON21")
  SetBinding("SHIFT-CTRL-F9", "ACTIONBUTTON22")
  SetBinding("ALT-F1", "ACTIONBUTTON23")
  SetBinding("C", "ACTIONBUTTON24")
  SetBinding("CTRL-ALT-6", "TOGGLECHARACTER0")
  SetBinding("NUMPAD8", "ACTIONBUTTON25")
  SetBinding("SHIFT-CTRL-F11", "ACTIONBUTTON26")
  SetBinding("NUMPADADD", "CLEARFOCUS")
  SetBinding("CTRL-ALT-7", "TOGGLECOLLECTIONS")
  SetBinding("NUMPAD0", "ACTIONBUTTON27")
  SetBinding("SHIFT-CTRL-F6", "ACTIONBUTTON28")
  SetBinding("CTRL-F10", "ACTIONBUTTON29")
  SetBinding("NUMPAD3", "ACTIONBUTTON30")
  SetBinding("NUMPAD7", "ACTIONBUTTON31")
  SetBinding("ALT-F3", "ACTIONBUTTON32")
  SetBinding("F6", "ACTIONBUTTON33")
  SetBinding("ALT-F10", "ACTIONBUTTON34")
  SetBinding("SHIFT-F10", "ACTIONBUTTON35")
  SetBinding("CTRL-F6", "ACTIONBUTTON36")
  SetBinding("I", "ACTIONBUTTON37")
  SetBinding("SHIFT-NUMPAD0", "TOGGLEENCOUNTERJOURNAL")
  SetBinding("(UNBOUND BY DEFAULT", "ACTIONBUTTON38")
  SetBinding("CTRL-F11", "ACTIONBUTTON39")
  SetBinding("SHIFT-F11", "ACTIONBUTTON40")
  SetBinding("ALT-F12", "ACTIONBUTTON41")
  SetBinding("SHIFT-F4", "ACTIONBUTTON42")
  SetBinding("SHIFT-F5", "ACTIONBUTTON43")
  SetBinding("SHIFT-F6", "ACTIONBUTTON44")
  SetBinding("NUMPADSUBTRACT", "FOCUSTARGET")
  SetBinding("SHIFT-F9", "ACTIONBUTTON45")
  SetBinding("SHIFT-NUMPAD2", "TOGGLESOCIAL")
  SetBinding("SHIFT-V", "ACTIONBUTTON46")
  SetBinding("ESCAPE", "TOGGLEGAMEMENU")
  SetBinding("CTRL-F5", "ACTIONBUTTON47")
  local mId = GetMacroIndexByName("Great Vault")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Great Vault", "inv_misc_questionmark", "/run LoadAddOn(\"Blizzard_WeeklyRewards\"); WeeklyRewardsFrame:Show()", 1)
  SetBindingMacro("CTRL-ALT-3", "Great Vault")
  SetBinding("ALT-F11", "ACTIONBUTTON48")
  SetBinding("F9", "ACTIONBUTTON49")
  SetBinding("J", "ACTIONBUTTON50")
  SetBinding("SHIFT-CTRL-F10", "ACTIONBUTTON51")
  SetBinding("SHIFT-CTRL-F7", "ACTIONBUTTON52")
  SetBinding("SHIFT-CTRL-F4", "ACTIONBUTTON53")
  SetBinding("SHIFT-CTRL-F8", "ACTIONBUTTON54")
  SetBinding("NUMPAD1", "ACTIONBUTTON55")
  SetBinding("CTRL-F2", "ACTIONBUTTON56")
  SetBinding("F12", "ACTIONBUTTON57")
  SetBinding("F", "INTERACTTARGET")
  SetBinding("F", "ACTIONBUTTON58")
  SetBinding("B", "ACTIONBUTTON59")
  SetBinding("CTRL-F3", "ACTIONBUTTON60")
  SetBinding("SHIFT-NUMPAD5", "ACTIONBUTTON61")
  SetBinding("SHIFT-CTRL-F3", "ACTIONBUTTON62")
  SetBinding("SPACE", "ACTIONBUTTON63")
  SetBinding("F7", "ACTIONBUTTON64")
  SetBinding("SHIFT-NUMPAD6", "ACTIONBUTTON65")
  SetBinding("SHIFT-NUMPAD1", "TOGGLEGROUPFINDER")
  SetBinding("ALT-F4", "ACTIONBUTTON66")
  SetBinding("NUMPAD5", "ACTIONBUTTON67")
  SetBinding("M", "CLICK CompanionsMicroButton:LeftButton")
  SetBinding("S", "MOVEBACKWARD")
  SetBinding("W", "MOVEFORWARD")
  SetBinding("V", "ACTIONBUTTON68")
  SetBinding("B", "OPENALLBAGS")
  SetBinding("ESCAPE", "ACTIONBUTTON69")
  SetBinding("G", "ACTIONBUTTON70")
  SetBinding("SHIFT-T", "ACTIONBUTTON71")
  SetBinding("CTRL-F8", "ACTIONBUTTON72")
  SetBinding("CTRL-F9", "ACTIONBUTTON73")
  SetBinding("K", "ACTIONBUTTON74")
  SetBinding("ALT-F5", "ACTIONBUTTON75")
  SetBinding("NUMPADMULTIPLY", "ACTIONBUTTON76")
  SetBinding("H", "ACTIONBUTTON77")
  SetBinding("L", "ACTIONBUTTON78")
  SetBinding("SHIFT-CTRL-F1", "ACTIONBUTTON79")
  SetBinding("NUMPADDIVIDE", "ACTIONBUTTON80")
  SetBinding("F11", "ACTIONBUTTON81")
  local mId = GetMacroIndexByName("Reload UI")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Reload UI", "inv_misc_questionmark", "/reload", 1)
  SetBindingMacro("CTRL-ALT-2", "Reload UI")
  SetBinding("ALT-F7", "ACTIONBUTTON82")
  SetBinding("R", "ACTIONBUTTON83")
  SetBinding("SHIFT-F8", "ACTIONBUTTON84")
  SetBinding("U", "ACTIONBUTTON85")
  SetBinding("SHIFT-F12", "ACTIONBUTTON86")
  SetBinding("PRINT SCREEN", "SCREENSHOT")
  SetBinding("SHIFT-CTRL-F2", "ACTIONBUTTON87")
  SetBinding("X", "ACTIONBUTTON88")
  SetBinding("NUMPAD2", "ACTIONBUTTON89")
  SetBinding("ALT-F6", "ACTIONBUTTON90")
  SetBinding("GUILD", "ACTIONBUTTON91")
  SetBinding("CTRL-F4", "ACTIONBUTTON92")
  SetBinding("CTRL-ALT-0", "TOGGLESPELLBOOK")
  SetBinding("P", "ACTIONBUTTON93")
  SetBinding("NUMPAD4", "ACTIONBUTTON94")
  SetBinding("NUMPAD9", "ACTIONBUTTON95")
  SetBinding("Q", "STRAFELEFT")
  SetBinding("E", "STRAFERIGHT")
  local mId = GetMacroIndexByName("Stuck")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Stuck", "spell_shadow_teleport", "/run Stuck()", 1)
  SetBindingMacro("CTRL-ALT-9", "Stuck")
  SetBinding("ALT-F2", "ACTIONBUTTON96")
  SetBinding("SHIFT-F1", "ACTIONBUTTON97")
  SetBinding("SHIFT-F2", "ACTIONBUTTON98")
  SetBinding("SHIFT-F3", "ACTIONBUTTON99")
  SetBinding("SHIFT-F (DEFAULT SETTING FOR INTERACT KEY AS F", "ACTIONBUTTON100")
  SetBinding("F2", "ACTIONBUTTON101")
  SetBinding("F3", "ACTIONBUTTON102")
  SetBinding("F4", "ACTIONBUTTON103")
  SetBinding("F5", "ACTIONBUTTON104")
  SetBinding("CTRL-ALT-8", "TARGETNEARESTENEMY")
  SetBinding("TAB", "ACTIONBUTTON105")
  SetBinding("F1", "ACTIONBUTTON106")
  SetBinding("SHIFT-TAB", "TARGETPREVIOUSENEMY")
  SetBinding("F1 (OR SOMETIMES JUST THE ASSIGNED KEY IF SET IN OPTIONS)", "TARGETSELF")
  SetBinding("ALT-Z", "ACTIONBUTTON107")
  SetBinding("SHIFT-MOUSE WHEEL DOWN (SCROLL DOWN)", "ACTIONBUTTON108")
  SetBinding("SHIFT-MOUSE WHEEL UP (SCROLL UP)", "ACTIONBUTTON109")
  SetBinding("ENTER", "ACTIONBUTTON110")
  local mId = GetMacroIndexByName("Toggle Details")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Toggle Details", "inv_misc_questionmark", "/details toggle", 1)
  SetBindingMacro("CTRL-ALT-4", "Toggle Details")
  local mId = GetMacroIndexByName("Toggle Music")
  if mId > 0 then DeleteMacro(mId) end
  CreateMacro("Toggle Music", "inv_misc_drum_01", "/run SetCVar(\"Sound_EnableMusic\", 1 - GetCVar(\"Sound_EnableMusic\"))", 1)
  SetBindingMacro("CTRL-ALT-5", "Toggle Music")
  SetBinding("L", "TOGGLEQUESTLOG")
  SetBinding("NUMPAD6", "ACTIONBUTTON111")
  SetBinding("A", "TURNLEFT")
  SetBinding("D", "TURNRIGHT")
  SetBinding("F12", "ACTIONBUTTON112")
  SetBinding("ALT-F9", "ACTIONBUTTON113")
  SetBinding("CTRL-F1", "ACTIONBUTTON114")
  SetBinding("F10", "ACTIONBUTTON115")
  SetBinding("M", "TOGGLEWORLDMAP")
  SetBinding("SHIFT-NUMPAD3", "CAMERAZOOMIN")
  SetBinding("SHIFT-NUMPAD4", "CAMERAZOOMOUT")
  
  -- Automated Action Bar Placement
  -- This will try to place spells automatically
  print("StreamDeck: Placing abilities on action bars...")
  local placed = 0
  local failed = 0
  
  -- AH Mount → Slot 14 (needs manual placement - item/macro)
 failed = failed + 1
  -- Ardent Defender → Slot 16
  if IsPlayerSpell(31850) then
    C_Spell.PickupSpell(31850)
    PlaceAction(16)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Avenger's Shield → Slot 17
  if IsPlayerSpell(31935) then
    C_Spell.PickupSpell(31935)
    PlaceAction(17)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Blessing of Freedom → Slot 20
  if IsPlayerSpell(1044) then
    C_Spell.PickupSpell(1044)
    PlaceAction(20)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Blessing of Sacrifice → Slot 21
  if IsPlayerSpell(6940) then
    C_Spell.PickupSpell(6940)
    PlaceAction(21)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Blinding Light → Slot 22
  if IsPlayerSpell(115750) then
    C_Spell.PickupSpell(115750)
    PlaceAction(22)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Cleanse Toxins → Slot 26
  if IsPlayerSpell(213644) then
    C_Spell.PickupSpell(213644)
    PlaceAction(26)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Consecration → Slot 28
  if IsPlayerSpell(26573) then
    C_Spell.PickupSpell(26573)
    PlaceAction(28)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Divine Shield → Slot 33
  if IsPlayerSpell(642) then
    C_Spell.PickupSpell(642)
    PlaceAction(33)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Flying Mount → Slot 41 (needs manual placement - item/macro)
 failed = failed + 1
  -- Ground Mount → Slot 48 (needs manual placement - item/macro)
 failed = failed + 1
  -- Guardian of Ancient Kings → Slot 49
  if IsPlayerSpell(86659) then
    C_Spell.PickupSpell(86659)
    PlaceAction(49)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Hammer of Justice → Slot 51
  if IsPlayerSpell(853) then
    C_Spell.PickupSpell(853)
    PlaceAction(51)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Hammer of the Righteous → Slot 52
  if IsPlayerSpell(53595) then
    C_Spell.PickupSpell(53595)
    PlaceAction(52)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Hammer of Wrath → Slot 53
  if IsPlayerSpell(24275) then
    C_Spell.PickupSpell(24275)
    PlaceAction(53)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Hand of Reckoning → Slot 54
  if IsPlayerSpell(62124) then
    C_Spell.PickupSpell(62124)
    PlaceAction(54)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Health Potion → Slot 55 (needs manual placement - item/macro)
 failed = failed + 1
  -- Invis Potion → Slot 60 (needs manual placement - item/macro)
 failed = failed + 1
  -- Judgment → Slot 62
  if IsPlayerSpell(20271) then
    C_Spell.PickupSpell(20271)
    PlaceAction(62)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Lay on Hands → Slot 64
  if IsPlayerSpell(633) then
    C_Spell.PickupSpell(633)
    PlaceAction(64)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Rebuke → Slot 81
  if IsPlayerSpell(96231) then
    C_Spell.PickupSpell(96231)
    PlaceAction(81)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Repair Mount → Slot 82 (needs manual placement - item/macro)
 failed = failed + 1
  -- Shield of Righteousness → Slot 87
  if IsPlayerSpell(53600) then
    C_Spell.PickupSpell(53600)
    PlaceAction(87)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  -- Smart Mount → Slot 90 (needs manual placement - item/macro)
 failed = failed + 1
  -- Speed Potion → Slot 92 (needs manual placement - item/macro)
 failed = failed + 1
  -- Word of Glory → Slot 115
  if IsPlayerSpell(85673) then
    C_Spell.PickupSpell(85673)
    PlaceAction(115)
    ClearCursor()
    placed = placed + 1
  else
    -- Spell not learned yet, skip
    failed = failed + 1
  end
  
  print(string.format("StreamDeck: Placed %d abilities, %d need manual setup", placed, failed))
  
  print("StreamDeck: Keybinds installed successfully!")
  SaveBindings(2)
end

Install()